_target_: wrappers.pretrained.build_model
_modelstr_: "pcad1_l20_from_pretrained"
from_scratch: False
pretrained_name_or_path: "kuleshov-group/PlantCaduceus_l20"
pad_token_id: -100  # [PAD] token ID
max_seq_len: 512
mlm: True
